config/routes.rb
Rails.application.routes.draw do
  resources :topics, only: [:index, :show]

  devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'register' }
  resources :portfolios, except: [:show] do
    put :sort, on: :collection
  end
  get 'angular-items', to: 'portfolios#angular'
  get 'portfolio/:id', to: 'portfolios#show', as: 'portfolio_show'
  
  get 'about-me', to: 'pages#about'
  get 'contact', to: 'pages#contact'
  
  get 'pages/contact'
  
  resources :blogs do
  	member do
  	  get :toggle_status
  	end
  end

  mount ActionCable.server => '/cable'

  root to: 'pages#home'
end

app/views/shared/_application_footer.html.erb
<div class="mastfoot">
  <div class="inner">
    <p class="app-footer"><p><%= copyright_generator %></p>
  </div>
</div>

 

app/views/shared/_application_nav.html.erb
<div class="masthead clearfix">
  <div class="inner">
    <h3 class="masthead-brand">Philip Grant</h3>
    <nav class="nav nav-masthead app-nav">
      <%= nav_helper 'nav-link', 'span' %>
      <%= login_helper 'nav-link' %>
    </nav>
  </div>
</div>

app/views/shared/_blog_footer.html.erb
<footer class="blog-footer">
  <p>
    <%= copyright_generator %>
  </p>
  <p>
    <a href="#">Back to top</a>
  </p>
</footer>

app/views/shared/_blog_masthead.html.erb
<div class="blog-header">
  <div class="container">
    <h1 class="blog-title">My Blog</h1>
    <p class="lead blog-description">Learning is like Lego. The more pieces you connect, the more exciting life becomes!</p>
    <span>
      <%= link_to 'Write a new blog', new_blog_path if logged_in?(:site_admin)%>
    </span>
    <span>
      <%= link_to "Topics", topics_path %>
    </span>
  </div>
</div>

app/views/shared/_blog_nav.html.erb
<nav class="navbar navbar-expand-md navbar-dark bg-dark">
  <div class="container">
    <%= link_to "Philip Grant", root_path, class: 'navbar-brand' %>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
 
    <div class="collapse navbar-collapse" id="navbarsExampleDefault">
     <ul class="navbar-nav ml-auto">
       <%= nav_helper 'nav-link', 'span' %>
       <%= login_helper 'nav-link' %>
     </ul>
    </div>
  </div>
</nav>

app/views/shared/_blog_sidebar.html.erb
<div class="col-sm-3 offset-sm-1 blog-sidebar">
  <div class="sidebar-module sidebar-module-inset">
    <h4>Focusing on the Future</h4>
    <p>Language and communication is a valuable means of learning and expressing oneself.
    Children need to learn how to make these connections.
    As we grow up, we can continue making connections, cutting through language and speech inhibitors,
    much can be learned from each other.</p>
  </div>

    <%= source_helper("alert alert-info blog-sidebar-source") %>

  <div class="sidebar-module">
    <h4>Topics</h4>
    <% @side_bar_topics.each do |topic| %>
      <p><%= link_to topic.title, topic_path(topic) %></p>
    <% end %>
  </div>

<!--
  <div class="sidebar-module">
    <h4>Learn more</h4>
    <ol class="list-unstyled social-links">
      <li><a href="#"><%= fa_icon "youtube" %></a></li>
      <li><a href="#"><%= fa_icon "instagram" %></a></li>
      <li><a href="#"><%= fa_icon "github" %></a></li>
    </ol>
  </div>
</div>
-->

app/views/shared/_nav.html.erb
<div class="<%= location %>">

</div>

app/views/shared/_portfolio_footer.html.erb
<footer class="text-muted">
  <div class="container">
	<p class="float-right">
	  <%= link_to "See All Portfolio Items", portfolios_path %> |
  	  <a href="#">Back to top</a>
	</p>
	<p>
	  <%= copyright_generator %>
	</p>
  </div>
</footer>

app/views/shared/_portfolio_masthead.html.erb
<section class="jumbotron text-center">
  <div class="container">
    <h1 class="jumbotron-heading">My Portfolio</h1>
    <p class="lead text-muted">A wide range of education-based experience both inside and outside the classroom.  
        Besides supportive roles in education, I have also branched off to develop various skills along the way.</p>
    <p>
      <%= link_to 'Find out more about me', about_me_path, class: 'btn btn-primary' %>
      <%= link_to 'My Blog', blogs_path, class: 'btn btn-secondary' %>
    </p>
  </div>
</section>

app/views/shared/_portfolio_nav.html.erb
<div class="collapse bg-dark" id="navbarHeader">
  <div class="container">
    <div class="row">
      <div class="col-sm-8 py-4">
        <h4 class="text-white">About</h4>
        <p class="text-muted">Philip has experience in primary school classroom settings, one on one instruction, language teaching and
        supporting exceptional students.  He has also branched off to other non-educational endeavors including software development,
        vehicle imports, plus some renovation trade experience.</p>
      </div>
      <div class="col-sm-4 py-4">
        <h4 class="text-white">Explore</h4>
        <ul class="list-unstyled">
          <%= nav_helper 'text-white', 'li' %>
          <li><%= login_helper 'text-white' %></li>
        </ul>
      </div>
    </div>
  </div>
</div>

<div class="navbar navbar-dark bg-dark shadow-sm">
  <div class="container d-flex justify-content-between">
    <a href="#" class="navbar-brand">Philip Grant</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarHeader" aria-controls="navbarHeader" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
  </div>
</div>